In [86]:
import torch

#basic tensors operations
#initializing tensors

a = torch.zeros(2, 3)
b = torch.ones(2, 3)
c = torch.rand(2, 3)
d = torch.full((3, 2), 5.0)
e = torch.tensor([[1, 2, 3], [4, 5, 6]])
g = torch.tensor([1, 2, 3])
h = torch.tensor([4, 5, 6])
j=torch.tensor([[1,2],[3,4]])
#copy one tensor to other 
f = torch.zeros_like(b)
print(f)


#operations 

#change datatypes
j=j.to(torch.float32)
e=e.to(torch.float32)

print(torch.sum(e))
print(torch.mean(e))
print(torch.median(e))
print(torch.min(e))
print(torch.max(e))
print(torch.var(e))



print(f"the location of the maximum eliment is {torch.argmax(e)}")
print(f"the martix multipliction {torch.matmul(e,d)}")
print(f"the dot product of the 2 vectors are {torch.dot(g,h)}")
print(f"the transpose operation :{torch.transpose(e,0,1)}")
print(f"the inverse operation :{torch.inverse(j)}")

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor(21.)
tensor(3.5000)
tensor(3.)
tensor(1.)
tensor(6.)
tensor(3.5000)
the location of the maximum eliment is 5
the martix multipliction tensor([[30., 30.],
        [75., 75.]])
the dot product of the 2 vectors are 32
the transpose operation :tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
the inverse operation :tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [87]:
a1=torch.tensor([1,2,3],dtype=torch.float32)
print(torch.log(a1))
print(torch.exp(a1))
print(torch.sqrt(a1))
print(torch.sigmoid(a1))
print(torch.softmax(a1,dim=0))
print(torch.relu(a1))

tensor([0.0000, 0.6931, 1.0986])
tensor([ 2.7183,  7.3891, 20.0855])
tensor([1.0000, 1.4142, 1.7321])
tensor([0.7311, 0.8808, 0.9526])
tensor([0.0900, 0.2447, 0.6652])
tensor([1., 2., 3.])


In [88]:
#clone a tensor:

b1=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
clone=b1.clone()
print(clone)
#inplace Operations 

print(b1.add_(clone))
print(b1.relu_())

#Reshape:

print(b1.reshape(6,1))
print(b1.flatten())

#GPU uses

if torch.cuda.is_available():
    device=torch.device('cuda')
    torch.rand((3,3),device=device )
else:
    print("not")

#unqueeze 
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
tensor([[ 2.],
        [ 4.],
        [ 6.],
        [ 8.],
        [10.],
        [12.]])
tensor([ 2.,  4.,  6.,  8., 10., 12.])
not


torch.Size([1, 226, 226, 3])

In [89]:
import torch 
#Autograd for automatic backpropogation and derivatives

x=torch.tensor(5.0,requires_grad=True)
y=x**2+3*x
z=torch.sin(y)
z.backward()
print(x.grad)

tensor(-8.6702)


In [90]:
#datset and Dataloader



import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split

class CustomData(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        return self.features[index], self.labels[index]



import torch

x = torch.tensor([
    [0,0],
    [0,1],
    [1,0],
    [1,1],
    [0,0],
    [1,0],
    [0,1],
    [1,1],
    [0,0],
    [1,1],
    [1,0],
    [0,1],
    [0,0],
    [1,0],
    [1,1],
    [0,1],
    [0,0],
    [1,1],
    [1,0],
    [0,1],
    [1,1],
    [0,0],
    [1,0],
    [0,1],
    [1,1],
    [0,0],
    [1,0],
    [0,1],
    [1,1],
    [0,0]
], dtype=torch.float32)

# XOR labels
y = torch.tensor([
    0, 1, 1, 0,
    0, 1, 1, 0,
    0, 0, 1, 1,
    0, 1, 0, 1,
    0, 0, 1, 1,
    0, 0, 1, 1,
    0, 0, 1, 1,
    0, 0
], dtype=torch.float32)

print(x.shape)
print(y.shape)

xtrain, xtest, ytrain, ytest = train_test_split(
    x, y, test_size=0.25, random_state=42
)

traindataset = CustomData(xtrain, ytrain)
testdataset = CustomData(xtest, ytest)

traindataloader = DataLoader(traindataset, batch_size=2, shuffle=True,drop_last=True)
testdataloader = DataLoader(testdataset, batch_size=2, shuffle=False,drop_last=True)

torch.Size([30, 2])
torch.Size([30])


In [91]:
#model building

import torch.nn as nn
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network=nn.Sequential(
            nn.Linear(num_features,10),
            # nn.BatchNorm1d(10),
            nn.ReLU(),
            # nn.Dropout(.3),
            nn.Linear(10,1),
            nn.Sigmoid()
        )
    def forward(self,features):
        out=self.network(features)
        return out

In [ ]:
#setting perameters 

device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Model(xtrain.shape[1])
#move model to device
model=model.to(device)
loss_fun=nn.BCELoss()
#move loss function to device
loss_fun=loss_fun.to(device)
optimizer=torch.optim.Adam(model.parameters(),lr=0.1,weight_decay=1e-4)
#move optimizer to device
optimizer=optimizer.to(device)

In [93]:
#training

Epochs=10
for i in range(Epochs):
    loss1=[]
    for features ,labels in traindataloader:
        features,labesl=features.to(device),labels.to(device)
        y_pred=model(features)
        loss=loss_fun(y_pred,labels.unsqueeze(1))
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        loss1.append(loss.item())
    print(i,sum(loss1)/len(loss1))

0 0.6812050071629611
1 0.5142273740334944
2 0.41256764802065765
3 0.26028232073242014
4 0.1086681488562714
5 0.029179848984561184
6 0.011944232720204374
7 0.006757616361772472
8 0.004729819568720731
9 0.004024885997006839


In [ ]:
#testing
with torch.no_grad():
    for features ,labels in testdataloader:
        #data move to device 
        features,labesl=features.to(device),labesl.to(device)
        y_pred=model(features)
        pred=(y_pred>.5).float()


    

In [ ]:
#testing

accuracies = []


with torch.no_grad():
    for features, labels in testdataloader:
        #data move to device
        features = features.to(device)
        labels = labels.to(device)
        features = features.float()
        
        labels = labels.unsqueeze(1).float()

        pred = (model(features) > 0.5).float()

        accuracies.append((pred == labels).float().mean().item())

print(f"Accuracy: {sum(accuracies)/len(accuracies):.2f}")

Accuracy: 1.00
